name: Deploy to gh pages

on:
  push:
    branches: [ main ]

jobs:
  deploy-to-github-pages:
    runs-on: ubuntu-latest
    steps:
      # Check out the repository
      - uses: actions/checkout@v2

      # Setup the required .NET SDK
      - name: Setup .NET SDK
        uses: actions/setup-dotnet@v1
        with:
          dotnet-version: 8.0.x

      # Publish the Blazor WebAssembly project
      - name: Publish Blazor Project
        run: dotnet publish -c Release -o release --nologo

      # Clean up previous temporary deployment folder
      - name: Clean up previous deployment folder
        run: |
          if [ -d "github-pages-deploy-action-temp-deployment-folder" ]; then
            rm -rf github-pages-deploy-action-temp-deployment-folder
          fi

      # Deploy to GitHub Pages       
      - name: Deploy to GitHub Pages
        uses: JamesIves/github-pages-deploy-action@v4
        with:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          BRANCH: gh-pages
          FOLDER: release/wwwroot
