name: Deploy to GHP branch
on:
  push:
    branches: [ main ]
    paths-ignore:
      - '**/README.md'
jobs:
  deploy-to-ghp-branch:
    runs-on: ubuntu-latest
    steps:
      # Check out the repository
      - uses: actions/checkout@v2
      
      # Setup the required .NET SDK (change dotnet-version as needed)
      - name: Setup .NET SDK
        uses: actions/setup-dotnet@v1
        with:
          dotnet-version: 8.0.x
      
      # Publish the Blazor WebAssembly project
      - name: Publish Blazor Project
        run: dotnet publish -c Release -o release --nologo
      
      # Deploy to GitHub Pages
      - name: Deploy to GHP branch final
        uses: JamesIves/github-pages-deploy-action@3.7.1
        with:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          BRANCH: gh-pages
          FOLDER: release/wwwroot
